# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :centos => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end

          box.vm.provision "shell", inline: <<-SHELL
#          mkdir -p ~root/.ssh
#          cp ~vagrant/.ssh/auth* ~root/.ssh
           yum install epel-release -y -q
           yum install fish wget -y -q
# Install tools for building rpm
           yum install rpmdevtools rpm-build -y -q
           yum install tree yum-utils mc wget gcc vim git -y -q
# Install tools for building woth mock and make prepares    
           yum install mock -y -q
           usermod -a -G mock root
# Install tools for creating your own REPO
           yum install nginx -y -q
           yum install createrepo -y -q
# Create a package
	   rpmdev-setuptree
	   # prepare hello.py for packaging
	   mkdir /tmp/hello-0.1
	   cp /vagrant/hello.py /tmp/hello-0.1/
	   # create archive and move to ~/rpmbuild/SOURCES/
	   cd /tmp
	   tar -cvzf hello-0.1.tar.gz hello-0.1
	   mv /tmp/hello-0.1.tar.gz ~/rpmbuild/SOURCES/
	   # copy spec file
	   cp /vagrant/hello.spec ~/rpmbuild/SPECS/
       cd
       # build package
       rpmbuild -bb rpmbuild/SPECS/hello.spec 
      SHELL

      end
  end
end
