# -*- mode: ruby -*-
# vim: set ft=ruby :

home = ENV['HOME']

MACHINES = {
  :otus => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => home + '/VirtualBox VMs/sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
			:dfile => home + '/VirtualBox VMs/sata2.vdi',
            :size => 250, # Megabytes
			:port => 2
		}

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          # install packages
          yum install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd -y
      # create and start watchlog
          # copy file to monitor
          cp /vagrant/watchlog.log /var/log/
          # copy config for unit service
          cp /vagrant/watchlog /etc/sysconfig/
          # copy logic script
          cp /vagrant/watchlog.sh /opt/
          # copy service and timer
          cp /vagrant/watchlog.service /etc/systemd/system
          cp /vagrant/watchlog.timer /etc/systemd/system
          systemctl start watchlog.timer
      # spawn-fcgi
          # copy uncommented spawn-fcgi config file
          cp /vagrant/spawn-fcgi /etc/sysconfig/
          # copy spawn-fcgi systemd service
          cp /vagrant/spawn-fcgi.service /etc/systemd/system
          # start and check
          systemctl start spawn-fcgi
          systemctl status spawn-fcgi
      # apache two instances
          # copy config files and unit file
	  cp /vagrant/httpd@.service /etc/systemd/system
	  cp /vagrant/httpd-* /etc/sysconfig
	  cp /vagrant/first.conf /etc/httpd/conf/
	  cp /vagrant/second.conf /etc/httpd/conf/
	  # start 2 instances and check ports listened
	  systemctl start httpd@first
	  systemctl start httpd@second
	  ss -tnulp | grep httpd
  	  SHELL

      end
  end
end

